---
title: 'Open postdoc position: azole resistance in Aspergillus fumigatus'
author: ''
date: '2021-02-10'
slug: '2021-02-10-halle-postdoc-position'
categories: []
tags:   
    - jobs
subtitle: ''
summary: '*This position has been filled.*'
authors: []
lastmod: ''
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

We have a postdoc position available as part of a multi-center collaborative research project investigating the environmental origin of antifungal resistance in *Aspergillus fumigatus*. The position is in cooperation with the research groups of Holger Deising (Uni Halle), Oliver Kurzai (Uni Wü) and our group at the Leibniz-HKI. The primary place of work will be Jena, Germany. However, some field work and obligations in Halle, Germany will be required.  

<br>
**The required qualifications for the position is:**  
- Master’s degree (or equivalent) in biology, microbiology, molecular biology, phytopathology, or a related discipline. Completion of a doctoral degree is desired but not absolutely required  
- Expert knowledge of microbiology and molecular biology techniques. Experience working with S-2 organisms and/or fungi would be advantageous  
- Good written and spoken English communication skills  
- EU Class B driver’s license  


**The tasks for this position include:**  
- Adaptation of *Aspergillus* spp in the presence of antifungal compounds  
- Antifungal susceptibility testing  
- Molecular analyses, including DNA extraction, PCR, qRT-PCR, molecular cloning, and the construction of mutant strains  
- Environmental soil and air sampling  
- Preparation of project reports and publications  
- Presentation of scientific results at conferences and project meetings  

<br>
Questions and requests for additional information can be directed to myself **(amelia.barber@leibniz-hki.de)** or Holger Deising **(holger.deising@landw.uni-halle.de)**. 

<br>
Applications, including a cover letter with a brief statement of research experience and motivation, CV, degree certifications/transcripts, and the contact information of two possible references, should be submitted via E-mail as a single PDF to Prof. Dr. Holger Deising at holger.deising@landw.uni-halle.de.  


<br>
**Applications will be reviewed as they are received and will continue until the position is filled.**  


[Official job posting @ Uni-Halle](http://www.verwaltung.uni-halle.de/dezern3/Ausschr/21_5_1223_20_D_engl.pdf)  