---
title: 'February 2021: 2 open PhD positions'
author: ''
date: '2021-02-05'
slug: 'feb-2021-2-open-phd-positions'
categories: []
tags:   
    - jobs
subtitle: ''
summary: '*The application deadline for these positions has passed*'
authors: []
lastmod: ''
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

We are recruiting 2 PhD student to investigate how cross-kingdom interactions of environmental fungi in their native niche shapes pathogenicity in humans. One position will be mostly lab-based, while the other will be primarily computational. However, candidates with an interest or experience in both areas are also encouraged to apply!

**The required for qualifications for both positions are:**  
- Masters degree (or equivalent) with research-based thesis.  
- Very good communication skills in English. 

**The specific requirements for the bioinformatics PhD position are:**  
- Knowledge and expertise in the analysis of biological high-throughput data.  
- Knowledge in statistical methods in the context of biological systems.  
- Experience with programming (Python, Perl, R, or C++).  

**The specific requirements for the wet lab positions are:**  
- Laboratory experience in microbiology, molecular biology, and/or biochemistry  
- Basic knowledge of programming (R, python) for data analysis and statistics  
- Prior experience working with microbial communities and/or metagenomic data would be an asset, but not required  

<br>

**What we offer:**  

We provide a convivial work atmosphere in an interdisciplinary and international research environment. The Leibniz-HKI is embedded in the outstanding scientific environment of the Beutenberg Campus providing state-of-the-art research facilities and a highly integrative network of life science groups. The group is part of the Microverse Cluster of Excellence and the PhD candidate will become a member of the Jena School of Microbial Communication. Our group is located within the Systems Biology & Bioinformatics Group (SBI) at the Leibniz-HKI and the successful candidates will be fully integrated in the SBI and benefit from shared samples, data, and methods with the other PhD students and post-doctoral researchers of the group.  

**Applications can be made until March 15, 2020**.  
[Apply for the bioinformatics PhD position](https://jobs.hki-jena.de/jobs/Doctoral-Researcher-fdivm-in-Bioinformatics-eng-j279.html)  
[Apply for the microbial ecology (wet lab) PhD position](https://jobs.hki-jena.de/jobs/Doctoral-Researcher-fdivm-in-Microbial-Ecology-eng-j280.html)  

***

More information about the project, our group, and what we offer can be found in the video below:

```{r echo=FALSE}
blogdown::shortcode('youtube', 'EcfDhdQCV_4')
```
<br>

 


**Applications can be made until December 3, 2020**.  

Additional information, including how to apply, at:<br>
<https://www.microverse-cluster.de/en/jobs.html> or <https://apply.jsmc.uni-jena.de/>
<br>